---
profile_puppetagent::puppetmaster: puppetmaster.foreman.vagrant
profile_puppetmaster::ca_server: puppet.foreman.vagrant
profile_puppetmaster::certname: puppet.foreman.vagrant
profile_puppetmaster::puppetdb: puppet.foreman.vagrant
profile_puppetmaster::puppetmaster: puppet.foreman.vagrant